name: Deploy website
on: push
jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: install
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: install

            - name: test
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: jest

            - name: website
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: website:create-and-publish
