name: CI
on: push
jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: install
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: install

            - name: test
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: jest

            - name: lib
              uses: borales/actions-yarn@v2.0.0
              with:
                  cmd: lib:build

            - run: npm version patch
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
